export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const LOAD_SKILLS_SUCCESS = "LOAD_SKILLS_SUCCESS";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const CREATE_SKILL_SUCCESS = "CREATE_SKILL_SUCCESS";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const DELETE_EMPLOYEE_OPTIMISTIC = "DELETE_EMPLOYEE_OPTIMISTIC";
export const DELETE_SKILL_OPTIMISTIC = "DELETE_SKILL_OPTIMISTIC";
